name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore src/*.sln
    - name: Build with dotnet
      run: dotnet build src/*.sln --configuration Release --no-restore
    - name: Test with dotnet
      run: dotnet test src/Courier.RestClient.Tests/Courier.RestClient.Tests.csproj --no-restore --verbosity normal
    - name: Pack with dotnet
      run: dotnet pack src/Courier.RestClient/Courier.RestClient.csproj --output packages --configuration Release --version ${{ secrets.BUILD_VERSION }}
    - name: Push with dotnet
      run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
